In [1]:
import numpy as np

In [30]:
x = np.array([1, 2, 3, 4, 5])

In [27]:
y = np.array([1000, -2, 1, 0, 50])[::-1]

In [28]:
y

array([  50,    0,    1,   -2, 1000])

In [29]:
np.corrcoef(x, y)

array([[1.        , 0.67853914],
       [0.67853914, 1.        ]])

In [31]:
x = np.linspace(-1, 1, 10)

In [38]:
y = x ** 2

In [39]:
np.corrcoef(x, y)

array([[ 1.00000000e+00, -1.45420318e-16],
       [-1.45420318e-16,  1.00000000e+00]])

In [40]:
from scipy.stats import pearsonr

In [50]:
x = np.linspace(-100, 100, 10)
y = x ** 2

In [51]:
pearsonr(x, y) # if p < 0.05, the result is significant

PearsonRResult(statistic=-5.551115123125783e-17, pvalue=1.0)

In [49]:
np.corrcoef(x, y)

array([[1., 1.],
       [1., 1.]])

In [ ]:
x = np.random.int