In [4]:
!conda list | grep numpy

numpy                     1.24.3          py311h08b1b3b_1  
numpy-base                1.24.3          py311hf175353_1  
numpydoc                  1.5.0           py311h06a4308_0  


In [6]:
!conda --version

conda 23.7.4


In [11]:
!python -m pip list | grep numpy

numpy                                    1.24.3
numpydoc                                 1.5.0


In [13]:
!pip install numpy

/bin/bash: line 1: /home/noname/.local/bin/pip: cannot execute: required file not found


In [22]:
import numpy as np

In [20]:
a = 0

In [36]:
p_list = [1.5, 2, 3, "4"]
array = np.array(p_list)

In [37]:
print(array)

['1.5' '2' '3' '4']


In [38]:
type(array)

numpy.ndarray

In [56]:
p_list = [[[1,2],
          [12,2],
          [13,1],
          [4, 1],
          [9, 3],
          [67,1]]]
array = np.array(p_list)

In [57]:
array.shape

(1, 6, 2)

In [68]:
ones = np.ones((32, 3, 3), dtype="float32")

In [69]:
ones.shape

(32, 3, 3)

In [78]:
zeroes = np.zeros([2,2], dtype='int8')

In [79]:
zeroes

array([[0, 0],
       [0, 0]], dtype=int8)

In [90]:
white_img = np.full((10,10, 1), 56)

In [97]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [101]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [108]:
numbers = np.arange(10, 20, 1)
numbers

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [111]:
even_indexes = np.arange(0, 10, 2)
print(even_indexes)
numbers[even_indexes]

[0 2 4 6 8]


array([10, 12, 14, 16, 18])

In [123]:
np.linspace(10, 15, 20)

array([10.        , 10.26315789, 10.52631579, 10.78947368, 11.05263158,
       11.31578947, 11.57894737, 11.84210526, 12.10526316, 12.36842105,
       12.63157895, 12.89473684, 13.15789474, 13.42105263, 13.68421053,
       13.94736842, 14.21052632, 14.47368421, 14.73684211, 15.        ])

In [129]:
np.random.rand(3, 3, 3, 1)

array([[[[0.17405058],
         [0.03703419],
         [0.61171075]],

        [[0.03823312],
         [0.51279793],
         [0.87031459]],

        [[0.4796774 ],
         [0.94590775],
         [0.30791233]]],


       [[[0.17543612],
         [0.94155054],
         [0.48889446]],

        [[0.61468316],
         [0.02816984],
         [0.85493447]],

        [[0.18424219],
         [0.47405012],
         [0.80527757]]],


       [[[0.61557963],
         [0.45126155],
         [0.18226231]],

        [[0.79450301],
         [0.75694602],
         [0.82453315]],

        [[0.85201441],
         [0.41700641],
         [0.23309268]]]])

In [141]:
random_ints = np.random.randint(5, 128, size=(5,6), dtype='int8')

In [142]:
random_ints.dtype

dtype('int8')

In [145]:
random_ = np.random.randn(5, 3)

In [146]:
random_.mean()

-0.10046964377298098

In [147]:
random_.std()

1.0016636517019655

In [148]:
random_.dtype

dtype('float64')

In [151]:

np.random.randint(0, 10, size=5)

array([0, 9, 1, 1, 8])

In [175]:
np.random.seed(100)
np.random.randint(0, 10, size=5)

array([8, 8, 3, 7, 7])

In [176]:
np.random.randint(0, 10, size=5)

array([0, 4, 2, 5, 2])

In [180]:
np.random.seed(100)
np.random.randint(0, 10, size=5)

array([8, 8, 3, 7, 7])

In [178]:
np.random.randint(0, 10, size=5)

array([0, 4, 2, 5, 2])

In [182]:
a = np.array([1, 2, 3])  
a.shape

(3,)

In [184]:
a = np.array([1, 2, 3])  
b = 5                   
print(a * b)  # Output: [6 7 8]

[ 5 10 15]


In [208]:
a = np.array([[1, 2], [2, 2], [3, 2]])   # Shape: (3, 1)
a.shape

(3, 2)

In [213]:
b = np.array([ 20, 30])  	# Shape: (3,)
b.shape

(2,)

In [214]:
# Broadcast shapes: (3, 1) + (1, 3) => (3, 3)
result = a + b

In [215]:
result.shape

(3, 2)

In [216]:
result

array([[21, 32],
       [22, 32],
       [23, 32]])

In [195]:
result

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [198]:
a * b

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [218]:
a

array([[1, 2],
       [2, 2],
       [3, 2]])

In [221]:
a = np.arange(0, 10, 1)

In [222]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [224]:
a[1:5: 2]

array([1, 3])

In [236]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [286]:
a = np.random.randint(-10, 10, size=(5,5))
a

array([[ -4,   0, -10,  -8,   9],
       [ -6,   8,  -6,  -7,  -1],
       [  6,   6,  -4,  -5,  -4],
       [ -3,   1,   9,  -8,   9],
       [  7,   3,  -5,   3,  -7]])

In [287]:
a[1:4,1:4] = 5

In [288]:
a

array([[ -4,   0, -10,  -8,   9],
       [ -6,   5,   5,   5,  -1],
       [  6,   5,   5,   5,  -4],
       [ -3,   5,   5,   5,   9],
       [  7,   3,  -5,   3,  -7]])

In [289]:
a % 2 == 0

array([[ True,  True,  True,  True, False],
       [ True, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [291]:
a[a > 0]

array([9, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 9, 7, 3, 3])

In [295]:
a[a < 0] = 0

In [296]:
a

array([[0, 0, 0, 0, 9],
       [0, 5, 5, 5, 0],
       [6, 5, 5, 5, 0],
       [0, 5, 5, 5, 9],
       [7, 3, 0, 3, 0]])

In [302]:
a = np.ones((6,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [303]:
a.reshape((12, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [309]:
a.reshape((2, 3, 2, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [310]:
a.max()

1.0

In [311]:
a.min()

1.0

In [315]:
a.argmin()

0

In [317]:
a.argmax()

0

In [318]:
a.shape

(6, 6)

In [319]:
a.dtype

dtype('float64')

In [320]:
a.size

36

In [321]:
a.ndim

2

In [324]:
a.shape

(6, 6)

In [326]:
np.expand_dims(a, axis=-1).shape

(6, 6, 1)

In [327]:
images = np.empty((32, 512, 512))

In [329]:
images.shape

(32, 512, 512)

In [340]:
new_images = np.expand_dims(images, axis=-1)
new_images.shape

(32, 512, 512, 1)

In [341]:
new_images.squeeze().shape

(32, 512, 512)