In [2]:
import numpy as np

In [3]:
arr = np.random.randint(0, 255, size=(512, 512))

In [4]:
arr

array([[129, 182, 140, ..., 105, 215,  72],
       [213, 144,  81, ..., 123,   2, 220],
       [ 87,  65, 207, ..., 209, 148,  41],
       ...,
       [142, 248, 240, ...,  28, 215,  94],
       [211,   2, 188, ..., 159,   2, 105],
       [128, 162, 166, ...,  77, 139, 168]])

In [5]:
np.save("rand_int.npy", arr)

In [6]:
arr2 = np.load("rand_int.npy")

In [7]:
arr2

array([[129, 182, 140, ..., 105, 215,  72],
       [213, 144,  81, ..., 123,   2, 220],
       [ 87,  65, 207, ..., 209, 148,  41],
       ...,
       [142, 248, 240, ...,  28, 215,  94],
       [211,   2, 188, ..., 159,   2, 105],
       [128, 162, 166, ...,  77, 139, 168]])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(arr2)

numpy.ndarray

In [10]:
np.sum(arr == arr2) /(512 *512 ) 

1.0

In [11]:
512 * 512

262144

In [12]:
np.savez("multi_ndarray.npz", source=arr, target=arr * .75)

In [13]:
data = np.load("multi_ndarray.npz")

In [14]:
data['target']

array([[ 96.75, 136.5 , 105.  , ...,  78.75, 161.25,  54.  ],
       [159.75, 108.  ,  60.75, ...,  92.25,   1.5 , 165.  ],
       [ 65.25,  48.75, 155.25, ..., 156.75, 111.  ,  30.75],
       ...,
       [106.5 , 186.  , 180.  , ...,  21.  , 161.25,  70.5 ],
       [158.25,   1.5 , 141.  , ..., 119.25,   1.5 ,  78.75],
       [ 96.  , 121.5 , 124.5 , ...,  57.75, 104.25, 126.  ]])

In [15]:
data

In [16]:
columns = ",".join([f"col{i}" for i in range(1, 513)])

In [17]:
np.savetxt("arr.csv", arr, delimiter=",", header=columns)

In [18]:
np.savetxt

<function numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)>

In [19]:
np.loadtxt

<function numpy.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)>

In [20]:
# np.loadtxt("arr.csv", dtype=str)
np.loadtxt('arr.csv', delimiter=",", skiprows=101, usecols=90).shape

(412,)

In [67]:
np.genfromtxt("arr.csv",
              delimiter=',',
              names=True,
             dtype=None,
             encoding=None)

array([('hammad', 22, 'idk'), ('zaheer',  5, '6.5'),
       ('taimur', 60, '5.2'), ('samad', 65, '3.5')],
      dtype=[('name', '<U6'), ('age', '<i8'), ('height', '<U3')])

In [34]:
np.genfromtxt

<function numpy.genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)>

In [68]:
arr.dtype

dtype('int64')

In [70]:
arr.astype('float64').dtype

dtype('float64')

In [71]:
arr2 = arr.astype('int8')

In [73]:
arr2.dtype

dtype('int8')

In [75]:
arr2

array([[-127,  -74, -116, ...,  105,  -41,   72],
       [ -43, -112,   81, ...,  123,    2,  -36],
       [  87,   65,  -49, ...,  -47, -108,   41],
       ...,
       [-114,   -8,  -16, ...,   28,  -41,   94],
       [ -45,    2,  -68, ...,  -97,    2,  105],
       [-128,  -94,  -90, ...,   77, -117,  -88]], dtype=int8)

In [76]:
np.array([0, 0, 2, 3, 4, 0, 0]).astype(bool)

array([False, False,  True,  True,  True, False, False])

In [86]:


np.array([[0], [0], [2], [3], [4], [0], [0]]) + np.array([2, 3, 3])

array([[2, 3, 3],
       [2, 3, 3],
       [4, 5, 5],
       [5, 6, 6],
       [6, 7, 7],
       [2, 3, 3],
       [2, 3, 3]])

In [87]:
a = np.array([[0], [0], [2], [3], [4], [0], [0]])
b = np.array([2, 3, 3])

In [140]:
output = np.empty((7, 3), dtype='int')
output

array([[884331051,         0,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3]])

In [141]:
np.add(a, b, out=output, where=output == 0)

array([[884331051,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3]])

In [139]:
output

array([[884331576,         0,         3],
       [        2,         3,         3],
       [        4,         3,         3],
       [        5,         3,         3],
       [        6,         3,         3],
       [        2,         3,         3],
       [        2,         3,         3]])

In [149]:
np.power((2, 3, 4), 2)
np.power([2, 3, 4], 2)
np.power(np.array([2, 3, 4]), 2)

array([ 4,  9, 16])

In [154]:
np.exp([2, 3, 4])

array([ 7.3890561 , 20.08553692, 54.59815003])

In [155]:
np.expm1([2, 3, 4])

array([ 6.3890561 , 19.08553692, 53.59815003])

In [157]:
np.maximum([2, 3, 4], [1, 5, 3])

array([2, 5, 4])

In [159]:
np.minimum([2, 3, 4], [1, 5, 3])

array([1, 3, 3])

In [168]:
np.round([2.3, 5.9, 9.5])

array([ 2.,  6., 10.])

In [165]:
np.floor([2.3, 5.9, 9.5])

array([2., 5., 9.])

In [167]:
np.ceil([2.3, 5.9, 9.1])

array([ 3.,  6., 10.])

In [173]:
a = np.array([[1, 2, 3], [4, 5, 1], [9, 7, 0]])
a

array([[1, 2, 3],
       [4, 5, 1],
       [9, 7, 0]])

In [175]:
np.amin(a, axis=0)

array([1, 2, 0])

In [176]:
np.amin(a, axis=1)

array([1, 1, 0])