In [2]:
import pandas as pd
import numpy as np

In [24]:
s = pd.Series([45, 50, 55, 60, 65, 70], index=range(0, 6))

In [25]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [26]:
s

0    45
1    50
2    55
3    60
4    65
5    70
dtype: int64

In [32]:
random_arr = np.random.randint(10, size=(100))

In [38]:
random_arr

array([8, 7, 0, 8, 3, 6, 6, 8, 4, 4, 0, 7, 2, 0, 0, 5, 7, 8, 6, 1, 6, 0,
       5, 5, 5, 8, 9, 7, 5, 3, 2, 5, 8, 7, 6, 3, 2, 9, 8, 8, 7, 4, 9, 0,
       2, 7, 4, 9, 2, 6, 4, 8, 1, 8, 9, 8, 0, 2, 2, 6, 3, 4, 4, 4, 0, 5,
       5, 2, 9, 4, 9, 7, 5, 5, 3, 1, 0, 5, 5, 2, 3, 3, 1, 1, 7, 6, 2, 0,
       0, 5, 6, 8, 6, 7, 5, 8, 8, 4, 8, 9])

In [53]:
random_sr = pd.Series(random_arr, index=[f"index-{x}"  for x in range(0, 100)])

In [56]:
random_sr

index-0     8
index-1     7
index-2     0
index-3     8
index-4     3
           ..
index-95    8
index-96    8
index-97    4
index-98    8
index-99    9
Length: 100, dtype: int64

In [63]:
random_arr ** 2

array([64, 49,  0, 64,  9, 36, 36, 64, 16, 16,  0, 49,  4,  0,  0, 25, 49,
       64, 36,  1, 36,  0, 25, 25, 25, 64, 81, 49, 25,  9,  4, 25, 64, 49,
       36,  9,  4, 81, 64, 64, 49, 16, 81,  0,  4, 49, 16, 81,  4, 36, 16,
       64,  1, 64, 81, 64,  0,  4,  4, 36,  9, 16, 16, 16,  0, 25, 25,  4,
       81, 16, 81, 49, 25, 25,  9,  1,  0, 25, 25,  4,  9,  9,  1,  1, 49,
       36,  4,  0,  0, 25, 36, 64, 36, 49, 25, 64, 64, 16, 64, 81])

In [59]:
e = np.array([2] * 100)

In [76]:
age = pd.Series([29, 24, 19, 0], index=["Alice", 5, 6.7, "Ghulam"])

In [78]:
age[6.7]

19

In [81]:
random_arr[0]

8

In [82]:
type({"names":["Abc", "def", "ghi", "hkl"], "age": [1, 2, 3, 4]})

dict

In [84]:
 pd.DataFrame({"names":["Abc", "def", "ghi", "hkl"], "age": [1, 2, 3, 4]})

,names,age
0,Abc,1
1,def,2
2,ghi,3
3,hkl,4


In [100]:
pd.DataFrame([("Abc",1), ("def",2), ["ghi",3], ["hkl",4]], 
             columns=['name', 'age'],
             index=['a', 'b', 'c', 'd']
            )

,name,age
a,Abc,1
b,def,2
c,ghi,3
d,hkl,4


In [166]:
df = pd.read_csv("multi_index_practice.csv", 
                 sep=',', 
                 header=1,
                 dtype={"Name": str, "Position": str, "Salary": int},
                 # usecols=['Name', 'Position', 'Salary'],
                 converters = {"Name":lambda x: ":" + x, "Salary": lambda x: int(x)/1000000}
                 )

df

/tmp/ipykernel_4701/4226668799.py:1: ParserWarning: Both a converter and dtype were specified for column Name - only the converter will be used.
  df = pd.read_csv("multi_index_practice.csv",
/tmp/ipykernel_4701/4226668799.py:1: ParserWarning: Both a converter and dtype were specified for column Salary - only the converter will be used.
  df = pd.read_csv("multi_index_practice.csv",


,Name,Age,Department,Position,Salary,Years of Experience
0,:Alice,25,HR,Manager,0.050,3
1,:Bob,30,IT,Developer,0.060,5
2,:Charlie,35,IT,Analyst,0.055,4
3,:David,40,Finance,Manager,0.065,10
4,:Eve,29,HR,Analyst,0.052,2
5,:Frank,33,Finance,Developer,0.058,6


In [156]:
df.dtypes

Name        object
Position    object
Salary       int64
dtype: object

In [161]:
df.head(2)

,Name,Position,Salary
0,:Alice,Manager,0.05
1,:Bob,Developer,0.06


In [164]:
df.tail(1)

,Name,Position,Salary
5,:Frank,Developer,0.058


In [167]:
df.describe()

,Age,Salary,Years of Experience
count,6.000000,6.000000,6.000000
mean,32.000000,0.056667,5.000000
std,5.215362,0.005502,2.828427
min,25.000000,0.050000,2.000000
25%,29.250000,0.052750,3.250000
50%,31.500000,0.056500,4.500000
75%,34.500000,0.059500,5.750000
max,40.000000,0.065000,10.000000


In [172]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [174]:
df['Department'].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [179]:
df.columns

Index(['Name', 'Age', 'Department', 'Position', 'Salary',
       'Years of Experience'],
      dtype='object')

In [181]:
df[['Name', 'Age']]

,Name,Age
0,:Alice,25
1,:Bob,30
2,:Charlie,35
3,:David,40
4,:Eve,29
5,:Frank,33


In [189]:
df.notnull().sum()

Name                   6
Age                    6
Department             6
Position               6
Salary                 6
Years of Experience    6
dtype: int64

In [190]:
df.map

<bound method DataFrame.map of        Name  Age Department   Position  Salary  Years of Experience
0    :Alice   25         HR    Manager   0.050                    3
1      :Bob   30         IT  Developer   0.060                    5
2  :Charlie   35         IT    Analyst   0.055                    4
3    :David   40    Finance    Manager   0.065                   10
4      :Eve   29         HR    Analyst   0.052                    2
5    :Frank   33    Finance  Developer   0.058                    6>

In [193]:
df.map(lambda x: x.replace(":", "") if type)

AttributeError: 'int' object has no attribute 'replace'

In [5]:
pd

<module 'pandas' from '/home/noname/anaconda3/lib/python3.11/site-packages/pandas/__init__.py'>

In [175]:
df = pd.read_csv("multi_index_practice.csv", 
                 sep=',', 
                 header=1,
                 dtype={"Name": str, "Position": str, "Salary": int},
                 )

In [66]:
df[['Age', 'Name', 'Salary', 'Salary'],

,Age,Name,Salary,Salary
0,25,Alice,50000,50000
1,30,Bob,60000,60000
2,35,Charlie,55000,55000
3,40,David,65000,65000
4,29,Eve,52000,52000
5,33,Frank,58000,58000


In [27]:
df.iloc[0]

Name                     Alice
Age                         25
Department                  HR
Position               Manager
Salary                   50000
Years of Experience          3
Name: 0, dtype: object

In [42]:
df[['Age', 'Name' ]].iloc[::-1]

,Age,Name
5,33,Frank
4,29,Eve
3,40,David
2,35,Charlie
1,30,Bob
0,25,Alice


In [74]:
df = df.set_index('Name')

In [75]:
df

,Age,Department,Position,Salary,Years of Experience
Name,,,,,
Alice,25,HR,Manager,50000,3
Bob,30,IT,Developer,60000,5
Charlie,35,IT,Analyst,55000,4
David,40,Finance,Manager,65000,10
Eve,29,HR,Analyst,52000,2
Frank,33,Finance,Developer,58000,6


In [76]:
df.loc['David':'Frank']

,Age,Department,Position,Salary,Years of Experience
Name,,,,,
David,40,Finance,Manager,65000,10
Eve,29,HR,Analyst,52000,2
Frank,33,Finance,Developer,58000,6


In [69]:
df['Name'] = df.index

In [71]:
df = df.set_index("Department")

In [77]:
df

,Age,Department,Position,Salary,Years of Experience
Name,,,,,
Alice,25,HR,Manager,50000,3
Bob,30,IT,Developer,60000,5
Charlie,35,IT,Analyst,55000,4
David,40,Finance,Manager,65000,10
Eve,29,HR,Analyst,52000,2
Frank,33,Finance,Developer,58000,6


In [83]:
df.reset_index(inplace=True)

In [84]:
df

,Department,Name,Age,Position,Salary,Years of Experience
0,HR,Alice,25,Manager,50000,3
1,IT,Bob,30,Developer,60000,5
2,IT,Charlie,35,Analyst,55000,4
3,Finance,David,40,Manager,65000,10
4,HR,Eve,29,Analyst,52000,2
5,Finance,Frank,33,Developer,58000,6


In [143]:
np.array(df['Salary'] > 55000) 

array([False,  True, False,  True, False,  True])

In [164]:
df[(df['Salary'] > 55000) & (df['Age'] > 30)]

,Department,Name,Age,Position,Salary,Years of Experience
3,Finance,David,40,Manager,65000,10
5,Finance,Frank,33,Developer,58000,6


In [118]:
(df['Salary'] > 55000).values and (df['Salary'] > 55000).values and (df['Age'] > 30).values

array([False,  True, False,  True, False,  True])

In [119]:
df['Age'] > 30

0    False
1    False
2     True
3     True
4    False
5     True
Name: Age, dtype: bool

In [157]:
df.iloc[0:4][['Age', 'Name']]

,Age,Name
0,25,Alice
1,30,Bob
2,35,Charlie
3,40,David


In [161]:
df[(df['Salary'] > 55000) & (df['Age'] > 30)]

,Department,Name,Age,Position,Salary,Years of Experience
3,Finance,David,40,Manager,65000,10
5,Finance,Frank,33,Developer,58000,6


In [193]:
df.set_index(['Department', 'Position'], inplace=True)

In [194]:
df

Name  Age  Salary  Years of Experience
Department Position                                            
HR         Manager      Alice   25   50000                    3
IT         Developer      Bob   30   60000                    5
           Analyst    Charlie   35   55000                    4
Finance    Manager      David   40   65000                   10
HR         Analyst        Eve   29   52000                    2
Finance    Developer    Frank   33   58000                    6

In [176]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [195]:
df.loc['IT'].loc['Developer']

Name                     Bob
Age                       30
Salary                 60000
Years of Experience        5
Name: Developer, dtype: object

In [199]:
df.loc[[('IT', 'Developer'), ('IT', 'Analyst')]]

Name  Age  Salary  Years of Experience
Department Position                                            
IT         Developer      Bob   30   60000                    5
           Analyst    Charlie   35   55000                    4

In [200]:
df.loc['IT'].loc[['Developer', 'Analyst']]

,Name,Age,Salary,Years of Experience
Position,,,,
Developer,Bob,30,60000,5
Analyst,Charlie,35,55000,4


In [191]:
df.reset_index(inplace=True)

In [192]:
df[df['Department'] == 'IT']

,Department,Position,Name,Age,Salary,Years of Experience
1,IT,Developer,Bob,30,60000,5
2,IT,Analyst,Charlie,35,55000,4


In [201]:
index = pd.MultiIndex.from_tuples([
	('USA', 2020),
	('USA', 2021),
	('Canada', 2020)
], names=['Country', 'Year'])
df = pd.DataFrame({'GDP': [21.4, 22.1, 1.6]}, index=index)

In [202]:
df

GDP
Country Year      
USA     2020  21.4
        2021  22.1
Canada  2020   1.6

In [203]:
df.reset_index()

,Country,Year,GDP
0,USA,2020,21.4
1,USA,2021,22.1
2,Canada,2020,1.6


In [207]:
df = pd.read_csv("multi_index_practice.csv", 
                 sep=',', 
                 header=[0,1],
                 dtype={"Name": str, "Position": str, "Salary": int},
                 # usecols=['Name', 'Position', 'Salary'],
                 converters = {"Name":lambda x: ":" + x, "Salary": lambda x: int(x)/1000000}
                 )

In [209]:
df.columns

MultiIndex([('Employee Info',                'Name'),
            ('Employee Info',                 'Age'),
            (     'Job Info',          'Department'),
            (     'Job Info',            'Position'),
            (     'Job Info',              'Salary'),
            ('Employee Info', 'Years of Experience')],
           )

In [216]:
df

Employee Info       Job Info                         Employee Info
           Name Age Department   Position Salary Years of Experience
0         Alice  25         HR    Manager  50000                   3
1           Bob  30         IT  Developer  60000                   5
2       Charlie  35         IT    Analyst  55000                   4
3         David  40    Finance    Manager  65000                  10
4           Eve  29         HR    Analyst  52000                   2
5         Frank  33    Finance  Developer  58000                   6

In [212]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [226]:
df.columns

MultiIndex([('Employee Info',                'Name'),
            ('Employee Info',                 'Age'),
            (     'Job Info',          'Department'),
            (     'Job Info',            'Position'),
            (     'Job Info',              'Salary'),
            ('Employee Info', 'Years of Experience')],
           )

In [227]:
df.set_index([('Job Info', 'Department'),('Job Info','Position')], inplace=True)

In [229]:
df

Employee Info     Job Info  \
                                                     Name Age   Salary   
(Job Info, Department) (Job Info, Position)                              
HR                     Manager                      Alice  25    50000   
IT                     Developer                      Bob  30    60000   
                       Analyst                    Charlie  35    55000   
Finance                Manager                      David  40    65000   
HR                     Analyst                        Eve  29    52000   
Finance                Developer                    Frank  33    58000   

                                                  Employee Info  
                                            Years of Experience  
(Job Info, Department) (Job Info, Position)                      
HR                     Manager                                3  
IT                     Developer                              5  
                       Analyst                                4  
Finance                Manager                               10  
HR                     Analyst                                2  
Finance                Developer                              6

In [222]:
df.loc['Alice':'Eve']

Employee Info   Job Info                    \
                                Age Department   Position Salary   
(Employee Info, Name)                                              
Alice                            25         HR    Manager  50000   
Bob                              30         IT  Developer  60000   
Charlie                          35         IT    Analyst  55000   
David                            40    Finance    Manager  65000   
Eve                              29         HR    Analyst  52000   

                            Employee Info  
                      Years of Experience  
(Employee Info, Name)                      
Alice                                   3  
Bob                                     5  
Charlie                                 4  
David                                  10  
Eve                                     2

In [225]:
df.reset_index(inplace=True)

In [231]:
df.shape

(6, 4)

In [309]:
df = pd.read_csv("multi_index_practice.csv", 
                 sep=',', 
                 header=[1],
                 dtype={"Name": str, "Position": str, "Salary": int},
                 # usecols=['Name', 'Position', 'Salary'],
                 converters = {"Name":lambda x: ":" + x, "Salary": lambda x: int(x)/1000000}
                 )

/tmp/ipykernel_3367/2682479670.py:1: ParserWarning: Both a converter and dtype were specified for column Name - only the converter will be used.
  df = pd.read_csv("multi_index_practice.csv",
/tmp/ipykernel_3367/2682479670.py:1: ParserWarning: Both a converter and dtype were specified for column Salary - only the converter will be used.
  df = pd.read_csv("multi_index_practice.csv",


In [243]:
df.columns

MultiIndex([('Employee Info',                'Name',   'Alice'),
            ('Employee Info',                 'Age',      '25'),
            (     'Job Info',          'Department',      'HR'),
            (     'Job Info',            'Position', 'Manager'),
            (     'Job Info',              'Salary',   '50000'),
            (     'Job Info', 'Years of Experience',       '3')],
           )

In [240]:
# df.set_index(('Employee Info',                'Name',          'First Name')).loc['Alice']

Employee Info  Name                 Last Name                  NaN
               Age                  Age                         25
Job Info       Department           Department                  HR
               Position             Position               Manager
               Salary               Salary                   50000
Employee Info  Years of Experience  Years of Experience          3
Name: Alice, dtype: object

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Name                 6 non-null      object 
 1   Age                  6 non-null      int64  
 2   Department           6 non-null      object 
 3   Position             6 non-null      object 
 4   Salary               6 non-null      float64
 5   Years of Experience  6 non-null      int64  
dtypes: float64(1), int64(2), object(3)
memory usage: 420.0+ bytes


In [249]:
int_values = [1, 2, 3, 4, 5]

text_values = ['alpha', 'beta', 'gamma', 'delta', 'epsilon']

float_values = [0.0, 0.25, 0.5, 0.75, 1.0]

df = pd.DataFrame({"int_col": int_values, "text_col": text_values,

                  "float_col": float_values})

In [264]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   int_col    5 non-null      int64  
 1   text_col   5 non-null      object 
 2   float_col  5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes


AttributeError: 'NoneType' object has no attribute 'index'

In [269]:
df['Department'].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [270]:
df['Department'].value_counts()

Department
HR         2
IT         2
Finance    2
Name: count, dtype: int64

In [271]:
df.value_counts()

Name      Age  Department  Position   Salary  Years of Experience
:Alice    25   HR          Manager    0.050   3                      1
:Bob      30   IT          Developer  0.060   5                      1
:Charlie  35   IT          Analyst    0.055   4                      1
:David    40   Finance     Manager    0.065   10                     1
:Eve      29   HR          Analyst    0.052   2                      1
:Frank    33   Finance     Developer  0.058   6                      1
Name: count, dtype: int64

In [275]:
df['Name'].apply(lambda x: x.replace(":", ""))

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
Name: Name, dtype: object

In [277]:
def removeColon(x):
    return x.replace(":", "")
df['Name'] = df['Name'].apply(removeColon)

In [278]:
df

,Name,Age,Department,Position,Salary,Years of Experience
0,Alice,25,HR,Manager,0.050,3
1,Bob,30,IT,Developer,0.060,5
2,Charlie,35,IT,Analyst,0.055,4
3,David,40,Finance,Manager,0.065,10
4,Eve,29,HR,Analyst,0.052,2
5,Frank,33,Finance,Developer,0.058,6


In [289]:
df.apply(lambda x: print(x), raw=False)

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
Name: Name, dtype: object
0    25
1    30
2    35
3    40
4    29
5    33
Name: Age, dtype: int64
0         HR
1         IT
2         IT
3    Finance
4         HR
5    Finance
Name: Department, dtype: object
0      Manager
1    Developer
2      Analyst
3      Manager
4      Analyst
5    Developer
Name: Position, dtype: object
0    0.050
1    0.060
2    0.055
3    0.065
4    0.052
5    0.058
Name: Salary, dtype: float64
0     3
1     5
2     4
3    10
4     2
5     6
Name: Years of Experience, dtype: int64


Name                   None
Age                    None
Department             None
Position               None
Salary                 None
Years of Experience    None
dtype: object

In [297]:
df.sort_values(['Department', "Age"], ascending=[True, False])

,Name,Age,Department,Position,Salary,Years of Experience
3,David,40,Finance,Manager,0.065,10
5,Frank,33,Finance,Developer,0.058,6
4,Eve,29,HR,Analyst,0.052,2
0,Alice,25,HR,Manager,0.050,3
2,Charlie,35,IT,Analyst,0.055,4
1,Bob,30,IT,Developer,0.060,5


In [298]:
df.sort_index()

,Name,Age,Department,Position,Salary,Years of Experience
0,Alice,25,HR,Manager,0.050,3
1,Bob,30,IT,Developer,0.060,5
2,Charlie,35,IT,Analyst,0.055,4
3,David,40,Finance,Manager,0.065,10
4,Eve,29,HR,Analyst,0.052,2
5,Frank,33,Finance,Developer,0.058,6


In [299]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [311]:
df.isnull().sum()

Name                   0
Age                    1
Department             0
Position               1
Salary                 0
Years of Experience    4
dtype: int64

In [315]:
df.dropna()

,Name,Age,Department,Position,Salary,Years of Experience
0,:,25.0,HR,Manager,0.050,3.0
5,:Frank,33.0,Finance,Developer,0.058,6.0


In [316]:
df.fillna(10)

,Name,Age,Department,Position,Salary,Years of Experience
0,:,25.0,HR,Manager,0.050,3.0
1,:Bob,30.0,IT,Developer,0.060,10.0
2,:Charlie,10.0,IT,Analyst,0.055,10.0
3,:David,40.0,Finance,Manager,0.065,10.0
4,:Eve,29.0,HR,10,0.052,10.0
5,:Frank,33.0,Finance,Developer,0.058,6.0
